# Window Management Rules
apps:
  Firefox:
    action: spawn_new

  Google Chrome:
    action: spawn_new
    spawn_script: osascript -e 'tell application "Google Chrome" to make new window'

  iTerm2:
    action: spawn_new
    # spawn_script: osascript -e 'tell application "iTerm2" to create window with default profile'

  Finder:
    action: spawn_new
    spawn_script: osascript -e 'tell application "Finder" to make new Finder window'

  Sublime Text:
    action: spawn_new

  Zed:
    action: spawn_new
    spawn_script: /opt/homebrew/bin/zed -n

  Obsidian:
    action: select

  Autodesk Fusion:
    action: select

  Slicer:
    action: select

  "3D Slicer":
    action: select

  VSCodium:
    action: select

  "Visual Studio Code":
    action: select
    spawn_script: /opt/homebrew/bin/code -n

  Overleaf:
    action: select

  Zotero:
    action: move_here

  Deepl:
    action: move_here

  "Beat Music Player":
    action: move_here


default_action: goto
