py:
  init: |
    %load_ext autoreload
    %autoreload 2
    import numpy as np
    import eartools.utils as earutils

  shebang: |
    #!/usr/bin/env -S uv run
    # /// script
    # dependencies = ["pyperclip", "pyfiglet"]
    # ///

  eartools: |
    [tool.uv.sources]
    eartools = { path = "/Users/philippaebischer/Documents/HRL/Projects/eartools", editable = true}

  autoreload: |
    %load_ext autoreload
    %autoreload 2

  uv-script: |
    [project.scripts]
    script_name = "prj.file:main" # assuming src/prj/file.py

    [build-system]
    requires = ["hatchling"]
    build-backend = "hatchling.build"

    [tool.hatch.build.targets.wheel]
    packages = ["src/prj"]

  plt-fig: |
    fig = plt.figure(figsize=(12, 8))
    ax = fig.add_subplot(111)

  plt-3dfig: |
    fig = plt.figure(figsize=(12, 8))
    ax = fig.add_subplot(111, projection="3d")

  plotly-fig: |
    fig = Figure()
    fig.show()



text:
  signature: |
    Philipp Aebischer

    Hearing Research Laboratory
    ARTORG Center for Biomedical Engineering Research
    University of Bern
    Murtenstrasse 50 | CH-3008 Bern
     
    Department of Otolaryngology, Head and Neck Surgery
    Bern University Hospital, Inselspital
    Freiburgstrasse 18 | CH-3010 Bern
     
    www.artorg.unibe.ch/research/hrl
    philipp.aebischer@unibe.ch
    +41 31 684 14 25



tex:
  figure: |
    \begin{figure*}[!t] % {figure} for single columns
    \centering
    \includegraphics[width=\linewidth]{img/image_name.pdf}
    \caption{Image caption.}
    \label{fig:image-name}
    \end{figure*}

  setup: |
    \usepackage{xcolor}
    \usepackage{amsmath}
    \usepackage[colorlinks=true, allcolors=blue]{hyperref}
    \usepackage{tabularx}

    \usepackage[english]{babel}

    \usepackage{graphicx}
    \graphicspath{{img/}}

    \usepackage{siunitx}
    \sisetup{per-mode=symbol-or-fraction}

    \newcommand{\figref}[1]{Figure\ \ref{#1}}
    \newcommand{\secref}[1]{section\ \ref{#1}}



