py:
  init: |
    from eartools import *

  shebang: |
    #!/usr/bin/env -S uv run
    # /// script
    # dependencies = ["pyperclip", "pyfiglet"]
    # ///

  eartools: |
    [tool.uv.sources]
      # source through github (static)
      # add tag = "v0.2.3" or rev = "969391f505b12b898dda8da9afd82352b485d454"
      # phipy-plots = { git = "https://github.com/phipi89/phipy-plots" }

      # source locally (editable)
      eartools = { path = "../../eartools", editable = true }
      phipy = { path = "../../phipy", editable = true }

  autoreload: |
    %load_ext autoreload
    %autoreload 2

  uv-script: |
    [project.scripts]
    script_name = "prj.file:main" # assuming src/prj/file.py

    [build-system]
    requires = ["hatchling"]
    build-backend = "hatchling.build"

    [tool.hatch.build.targets.wheel]
    packages = ["src/prj"]

  plt-fig: |
    fig = plt.figure(figsize=(12, 8))

    ax = fig.add_subplot(111)

    fig.show()

  plt-3dfig: |
    fig = plt.figure(figsize=(12, 8))

    ax = fig.add_subplot(111, projection="3d")

    fig.show()

  plotly-fig: |
    fig = Figure()



    fig.show()



tex:
  figure: |
    \begin{figure}[!t] % {figure} for single columns
    \centering
    \includegraphics[width=\linewidth]{img/image_name.pdf}
    \caption{Image caption.}
    \label{fig:image-name}
    \end{figure}

  setup: |
    \usepackage{xcolor}
    \usepackage{amsmath}
    \usepackage[colorlinks=true, allcolors=blue]{hyperref}
    \usepackage{tabularx}

    \usepackage[english]{babel}

    \usepackage{graphicx}
    \graphicspath{{img/}}

    \usepackage{siunitx}
    \sisetup{per-mode=symbol-or-fraction}

    \newcommand{\figref}[1]{Figure\ \ref{#1}}
    \newcommand{\secref}[1]{section\ \ref{#1}}



git:
  ignore: |
    # Python
    __pycache__/
    *.py[cod]

    # Virtual environments
    .venv/

    # Build and packaging artifacts
    build/
    dist/
    *.egg-info/

    # macOS
    .DS_Store
    ._*

    # editors
    .opencode/
    .zed/
    .vscode/
    .idea/

